module.exports = {
  Amiens: { id: 0, toString: function () { return ('Amiens'); }, lequipeId: 44 },
  Angers: { id: 1, toString: function () { return ('Angers'); }, lequipeId: 374 },
  Bordeaux: { id: 2, toString: function () { return ('Bordeaux'); }, lequipeId: 18 },
  Cean: { id: 3, toString: function () { return ('Cean'); }, lequipeId: 41 },
  Dijon: { id: 4, toString: function () { return ('Dijon'); }, lequipeId: 202 },
  Guingamp: { id: 5, toString: function () { return ('Guingamp'); }, lequipeId: 37 },
  Lille: { id: 6, toString: function () { return ('Lille'); }, lequipeId: 43 },
  Lyon: { id: 7, toString: function () { return ('Lyon'); }, lequipeId: 22 },
  Marseille: { id: 8, toString: function () { return ('Marseille'); }, lequipeId: 6 },
  Monaco: { id: 9, toString: function () { return ('Monaco'); }, lequipeId: 25 },
  Montpellier: { id: 10, toString: function () { return ('Montpellier'); }, lequipeId: 17 },
  Nantes: { id: 11, toString: function () { return ('Nantes'); }, lequipeId: 15 },
  Nice: { id: 12, toString: function () { return ('Nice'); }, lequipeId: 46 },
  Nimes: { id: 13, toString: function () { return ('Nimes'); }, lequipeId: 47 },
  Paris: { id: 14, toString: function () { return ('Paris SG'); }, lequipeId: 26 },
  Reims: { id: 15, toString: function () { return ('Reims'); }, lequipeId: 211 },
  Rennes: { id: 16, toString: function () { return ('Rennes'); }, lequipeId: 14 },
  StEtienne: { id: 17, toString: function () { return ('St Etienne'); }, lequipeId: 38 },
  Strasbourg: { id: 18, toString: function () { return ('Strasbourg'); }, lequipeId: 13 },
  Toulouse: { id: 19, toString: function () { return ('Toulouse'); }, lequipeId: 12 }
};
