module.exports = {
  Amiens: { id: 0, toString: function () { console.log('Amiens'); } },
  Angers: { id: 1, toString: function () { console.log('Angers'); } },
  Bordeaux: { id: 2, toString: function () { console.log('Bordeaux'); } },
  Cean: { id: 3, toString: function () { console.log('Cean'); } },
  Dijon: { id: 4, toString: function () { console.log('Dijon'); } },
  Guingamp: { id: 5, toString: function () { console.log('Guingamp'); } },
  Lille: { id: 6, toString: function () { console.log('Lille'); } },
  Lyon: { id: 7, toString: function () { console.log('Lyon'); } },
  Marseille: { id: 8, toString: function () { console.log('Marseille'); } },
  Monaco: { id: 9, toString: function () { console.log('Monaco'); } },
  Montpellier: { id: 10, toString: function () { console.log('Montpellier'); } },
  Nantes: { id: 11, toString: function () { console.log('Nantes'); } },
  Nice: { id: 12, toString: function () { console.log('Nice'); } },
  Nimes: { id: 13, toString: function () { console.log('Nimes'); } },
  Paris: { id: 14, toString: function () { console.log('Paris SG'); } },
  Reims: { id: 15, toString: function () { console.log('Reims'); } },
  Rennes: { id: 16, toString: function () { console.log('Rennes'); } },
  StEtienne: { id: 17, toString: function () { console.log('St Etienne'); } },
  Strasbourg: { id: 18, toString: function () { console.log('Strasbourg'); } },
  Toulouse: { id: 19, toString: function () { console.log('Toulouse'); } }
};
