module.exports = {
  Amiens: { id: 0, toString: function () { return ('Amiens'); } },
  Angers: { id: 1, toString: function () { return ('Angers'); } },
  Bordeaux: { id: 2, toString: function () { return ('Bordeaux'); } },
  Cean: { id: 3, toString: function () { return ('Cean'); } },
  Dijon: { id: 4, toString: function () { return ('Dijon'); } },
  Guingamp: { id: 5, toString: function () { return ('Guingamp'); } },
  Lille: { id: 6, toString: function () { return ('Lille'); } },
  Lyon: { id: 7, toString: function () { return ('Lyon'); } },
  Marseille: { id: 8, toString: function () { return ('Marseille'); } },
  Monaco: { id: 9, toString: function () { return ('Monaco'); } },
  Montpellier: { id: 10, toString: function () { return ('Montpellier'); } },
  Nantes: { id: 11, toString: function () { return ('Nantes'); } },
  Nice: { id: 12, toString: function () { return ('Nice'); } },
  Nimes: { id: 13, toString: function () { return ('Nimes'); } },
  Paris: { id: 14, toString: function () { return ('Paris SG'); } },
  Reims: { id: 15, toString: function () { return ('Reims'); } },
  Rennes: { id: 16, toString: function () { return ('Rennes'); } },
  StEtienne: { id: 17, toString: function () { return ('St Etienne'); } },
  Strasbourg: { id: 18, toString: function () { return ('Strasbourg'); } },
  Toulouse: { id: 19, toString: function () { return ('Toulouse'); } }
};
